---
kind: pipeline
name: "Build and test kwarray"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Install and run tests"
    image: kitware/dind
    commands:
      - pip install pip -U
      - pip install -r requirements.txt -U
      - pip install -e .
      - pytest -p no:doctest --cov-config .coveragerc --cov-report html --xdoctest --cov=kwarray --network kwarray

trigger:
  event:
    - pull_request
    - tag
