---
kind: pipeline
name: "Test in 3.6"

platform:
  os: linux
  arch: amd64

steps:
  - name: "Test python 3.6"
    image: python:3.6
    commands:
      - pip install pip -U
      - pip install -r requirements.txt -U

      # - ./run_developer_setup.sh
      # - ./run_tests.py
      
      # using pyargs tests the installed package instead of the source one
      - pip install -v --no-use-pep517 .
      - pytest --pyargs kwarray

trigger:
  event:
    - pull_request
    - tag
      
---
kind: pipeline
name: "Test in 2.7"

platform:
  os: linux
  arch: amd64
  
steps:
  - name: "Test python 2.x"
    image: python:2.7 
    commands:
      - pip install pip -U
      - pip install -r requirements.txt -U

      # - ./run_developer_setup.sh
      # - ./run_tests.py
      
      # using pyargs tests the installed package instead of the source one
      - pip install -v --no-use-pep517 .
      - pytest --pyargs kwarray

trigger:
  event:
    - pull_request
    - tag

